use crate::collision::tile_type::Walkable;
use bevy::prelude::*;

#[derive(Deref)]
pub struct TilemapSprite {
    #[deref]
    pub name: &'static str,
    pub pixel_x: u32,
    pub pixel_y: u32,
    pub walkable: Walkable,
}

pub struct TilemapDefinition {
    pub tile_width: u32,
    pub tile_height: u32,
    pub atlas_width: u32,
    pub atlas_height: u32,
    pub sprites: &'static [TilemapSprite],
}

impl TilemapDefinition {
    pub const fn tile_size(&self) -> UVec2 {
        UVec2::new(self.tile_width, self.tile_height)
    }

    pub const fn atlas_size(&self) -> UVec2 {
        UVec2::new(self.atlas_width, self.atlas_height)
    }

    pub fn sprite_index(&self, name: &str) -> Option<usize> {
        self.sprites.iter().position(|sprite| sprite.name == name)
    }
}

pub const MAIN_TILEMAP: TilemapDefinition = TilemapDefinition {
    tile_width: 16,
    tile_height: 16,
    atlas_width: 128,
    atlas_height: 240,
    sprites: &[
        // --- DIRT ---
        // Centers
        TilemapSprite {
            name: "dirt_1",
            pixel_x: 96,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_2",
            pixel_x: 112,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_3",
            pixel_x: 96,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_4",
            pixel_x: 112,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_5",
            pixel_x: 96,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_6",
            pixel_x: 112,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        // Dirt sides
        TilemapSprite {
            name: "dirt_side_l",
            pixel_x: 48,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_side_r",
            pixel_x: 80,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_side_t",
            pixel_x: 64,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_side_b",
            pixel_x: 64,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_corner_tl",
            pixel_x: 48,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_corner_tr",
            pixel_x: 80,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_corner_bl",
            pixel_x: 48,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_corner_br",
            pixel_x: 80,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        // Dirt Inner Corners (Smallest path turns)
        TilemapSprite {
            name: "dirt_inner_tl",
            pixel_x: 48,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_inner_tr",
            pixel_x: 64,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_inner_bl",
            pixel_x: 48,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_inner_br",
            pixel_x: 64,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        // Dirt Cliff/Bottom Edges
        TilemapSprite {
            name: "dirt_edge_l",
            pixel_x: 48,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_edge_mid",
            pixel_x: 64,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_edge_r",
            pixel_x: 80,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "dirt_cliff_face",
            pixel_x: 64,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        // --- GRASS FAMILY ---
        // Main Grass Island
        TilemapSprite {
            name: "grass_tl",
            pixel_x: 0,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_tc",
            pixel_x: 16,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_tr",
            pixel_x: 32,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_ml",
            pixel_x: 0,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_mc",
            pixel_x: 16,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_mr",
            pixel_x: 32,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_bl",
            pixel_x: 0,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_bc",
            pixel_x: 16,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_br",
            pixel_x: 32,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        // Grass Inner Corners
        TilemapSprite {
            name: "grass_inner_tl",
            pixel_x: 48,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_inner_tr",
            pixel_x: 64,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_inner_bl",
            pixel_x: 48,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_inner_br",
            pixel_x: 64,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        // Grass Bottom Cliffs/Edges
        TilemapSprite {
            name: "grass_edge_l",
            pixel_x: 0,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_edge_mid",
            pixel_x: 16,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_edge_r",
            pixel_x: 32,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        // Cliff Grass corners
        TilemapSprite {
            name: "cliff_grass_tl",
            pixel_x: 80,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "cliff_grass_tr",
            pixel_x: 96,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "cliff_grass_bl",
            pixel_x: 80,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "cliff_grass_br",
            pixel_x: 96,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        // Grass Variety
        TilemapSprite {
            name: "grass_1",
            pixel_x: 80,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_2",
            pixel_x: 96,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "grass_3",
            pixel_x: 112,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        // --- WATER FAMILY ---
        // --- WATER-GRASS ---
        TilemapSprite {
            name: "water_grass_tl",
            pixel_x: 0,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_grass_tc",
            pixel_x: 16,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_grass_tr",
            pixel_x: 32,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_grass_ml",
            pixel_x: 0,
            pixel_y: 176,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_mc",
            pixel_x: 16,
            pixel_y: 176,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_grass_mr",
            pixel_x: 32,
            pixel_y: 176,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_grass_bl",
            pixel_x: 0,
            pixel_y: 192,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_grass_bc",
            pixel_x: 16,
            pixel_y: 192,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_grass_br",
            pixel_x: 32,
            pixel_y: 192,
            walkable: Walkable::NonWalkable,
        },
        // --- WATER-DIRT ---
        TilemapSprite {
            name: "water_dirt_tl",
            pixel_x: 48,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_dirt_tc",
            pixel_x: 64,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_dirt_tr",
            pixel_x: 80,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_dirt_ml",
            pixel_x: 48,
            pixel_y: 176,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_dirt_mc",
            pixel_x: 16,
            pixel_y: 176,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_dirt_mr",
            pixel_x: 80,
            pixel_y: 176,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_dirt_bl",
            pixel_x: 48,
            pixel_y: 192,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_dirt_bc",
            pixel_x: 64,
            pixel_y: 192,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_dirt_br",
            pixel_x: 80,
            pixel_y: 192,
            walkable: Walkable::NonWalkable,
        },
        // --- INNER-WATER ---
        TilemapSprite {
            name: "water_inner_tl",
            pixel_x: 96,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_inner_tr",
            pixel_x: 112,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_inner_bl",
            pixel_x: 96,
            pixel_y: 176,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_inner_br",
            pixel_x: 112,
            pixel_y: 176,
            walkable: Walkable::NonWalkable,
        },
        // --- NARROW 1x1 WATER  ---
        TilemapSprite {
            name: "water_narrow_v",
            pixel_x: 96,
            pixel_y: 192,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_narrow_h",
            pixel_x: 112,
            pixel_y: 192,
            walkable: Walkable::NonWalkable,
        },
        // --- WATER w/ DECOR  ---
        TilemapSprite {
            name: "water_lily_flower",
            pixel_x: 112,
            pixel_y: 208,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_lily_plain",
            pixel_x: 112,
            pixel_y: 224,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "water_sparkle",
            pixel_x: 112,
            pixel_y: 240,
            walkable: Walkable::NonWalkable,
        },
    ],
};

pub const DECOR_TILEMAP: TilemapDefinition = TilemapDefinition {
    tile_width: 16,
    tile_height: 16,
    atlas_width: 256,
    atlas_height: 256,
    sprites: &[
        // --- 2 LARGE BUSHES ---
        TilemapSprite {
            name: "bush_lg_g_0_0",
            pixel_x: 16,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_lg_g_0_1",
            pixel_x: 32,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_lg_g_1_0",
            pixel_x: 16,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_lg_g_1_1",
            pixel_x: 32,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_lg_d_0_0",
            pixel_x: 16,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_lg_d_0_1",
            pixel_x: 32,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_lg_d_1_0",
            pixel_x: 16,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_lg_d_1_1",
            pixel_x: 32,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        // --- 2 LOGS ---
        TilemapSprite {
            name: "log_g_0_0",
            pixel_x: 64,
            pixel_y: 0,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "log_g_0_1",
            pixel_x: 80,
            pixel_y: 0,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "log_g_0_2",
            pixel_x: 96,
            pixel_y: 0,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "log_g_1_0",
            pixel_x: 64,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "log_g_1_1",
            pixel_x: 80,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "log_g_1_2",
            pixel_x: 96,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "log_d_0_0",
            pixel_x: 64,
            pixel_y: 32,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "log_d_0_1",
            pixel_x: 80,
            pixel_y: 32,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "log_d_0_2",
            pixel_x: 96,
            pixel_y: 32,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "log_d_1_0",
            pixel_x: 64,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "log_d_1_1",
            pixel_x: 80,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "log_d_1_2",
            pixel_x: 96,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        // --- 2 SMALL BUSHES ---
        TilemapSprite {
            name: "bush_sm_g_0_0",
            pixel_x: 128,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_sm_g_0_1",
            pixel_x: 144,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_sm_g_1_0",
            pixel_x: 128,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_sm_g_1_1",
            pixel_x: 144,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_sm_d_0_0",
            pixel_x: 128,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_sm_d_0_1",
            pixel_x: 144,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_sm_d_1_0",
            pixel_x: 128,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "bush_sm_d_1_1",
            pixel_x: 144,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        // --- 9 MUSHROOMS ---
        TilemapSprite {
            name: "mush_g1_0_0",
            pixel_x: 160,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g1_0_1",
            pixel_x: 176,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g1_1_0",
            pixel_x: 160,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g1_1_1",
            pixel_x: 176,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g2_0_0",
            pixel_x: 192,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g2_0_1",
            pixel_x: 208,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g2_1_0",
            pixel_x: 192,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g2_1_1",
            pixel_x: 208,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g3_0_0",
            pixel_x: 224,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g3_0_1",
            pixel_x: 240,
            pixel_y: 0,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g3_1_0",
            pixel_x: 224,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_g3_1_1",
            pixel_x: 240,
            pixel_y: 16,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e1_0_0",
            pixel_x: 160,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e1_0_1",
            pixel_x: 176,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e1_1_0",
            pixel_x: 160,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e1_1_1",
            pixel_x: 176,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e2_0_0",
            pixel_x: 192,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e2_0_1",
            pixel_x: 208,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e2_1_0",
            pixel_x: 192,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e2_1_1",
            pixel_x: 208,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e3_0_0",
            pixel_x: 224,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e3_0_1",
            pixel_x: 240,
            pixel_y: 32,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e3_1_0",
            pixel_x: 224,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_e3_1_1",
            pixel_x: 240,
            pixel_y: 48,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d1_0_0",
            pixel_x: 160,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d1_0_1",
            pixel_x: 176,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d1_1_0",
            pixel_x: 160,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d1_1_1",
            pixel_x: 176,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d2_0_0",
            pixel_x: 192,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d2_0_1",
            pixel_x: 208,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d2_1_0",
            pixel_x: 192,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d2_1_1",
            pixel_x: 208,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d3_0_0",
            pixel_x: 224,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d3_0_1",
            pixel_x: 240,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d3_1_0",
            pixel_x: 224,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "mush_d3_1_1",
            pixel_x: 240,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        // --- 2 WEEDS & 2 REEDS ---
        TilemapSprite {
            name: "weed_g1_0_0",
            pixel_x: 0,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_g1_0_1",
            pixel_x: 16,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_g1_1_0",
            pixel_x: 0,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_g1_1_1",
            pixel_x: 16,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_g2_0_0",
            pixel_x: 32,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_g2_0_1",
            pixel_x: 48,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_g2_1_0",
            pixel_x: 32,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_g2_1_1",
            pixel_x: 48,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_d1_0_0",
            pixel_x: 64,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_d1_0_1",
            pixel_x: 80,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_d1_1_0",
            pixel_x: 64,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_d1_1_1",
            pixel_x: 80,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_d2_0_0",
            pixel_x: 96,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_d2_0_1",
            pixel_x: 112,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_d2_1_0",
            pixel_x: 96,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "weed_d2_1_1",
            pixel_x: 112,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_g1_0_0",
            pixel_x: 64,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_g1_0_1",
            pixel_x: 80,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_g1_1_0",
            pixel_x: 64,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_g1_1_1",
            pixel_x: 80,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_g2_0_0",
            pixel_x: 96,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_g2_0_1",
            pixel_x: 112,
            pixel_y: 64,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_g2_1_0",
            pixel_x: 96,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_g2_1_1",
            pixel_x: 112,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_d1_0_0",
            pixel_x: 64,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_d1_0_1",
            pixel_x: 80,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_d1_1_0",
            pixel_x: 64,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_d1_1_1",
            pixel_x: 80,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_d2_0_0",
            pixel_x: 96,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_d2_0_1",
            pixel_x: 112,
            pixel_y: 80,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_d2_1_0",
            pixel_x: 96,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "reed_d2_1_1",
            pixel_x: 112,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        // --- PEBBLE ---
        TilemapSprite {
            name: "pebble_g_0_0",
            pixel_x: 128,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pebble_g_0_1",
            pixel_x: 144,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pebble_g_1_0",
            pixel_x: 128,
            pixel_y: 112,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pebble_g_1_1",
            pixel_x: 144,
            pixel_y: 112,
            walkable: Walkable::Walkable,
        },
        // --- 3 ROCKS ---
        TilemapSprite {
            name: "rock_g_0_0",
            pixel_x: 160,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "rock_g_0_1",
            pixel_x: 176,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "rock_g_1_0",
            pixel_x: 160,
            pixel_y: 112,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "rock_g_1_1",
            pixel_x: 176,
            pixel_y: 112,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "rock_d_0_0",
            pixel_x: 192,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "rock_d_0_1",
            pixel_x: 208,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "rock_d_1_0",
            pixel_x: 192,
            pixel_y: 112,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "rock_d_1_1",
            pixel_x: 208,
            pixel_y: 112,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "rock_e_0_0",
            pixel_x: 160,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "rock_e_0_1",
            pixel_x: 176,
            pixel_y: 96,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "rock_e_1_0",
            pixel_x: 160,
            pixel_y: 112,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "rock_e_1_1",
            pixel_x: 176,
            pixel_y: 112,
            walkable: Walkable::NonWalkable,
        },
        // --- 3 BOULDERS ---
        TilemapSprite {
            name: "boulder_g_0_0",
            pixel_x: 160,
            pixel_y: 128,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "boulder_g_0_1",
            pixel_x: 176,
            pixel_y: 128,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "boulder_g_1_0",
            pixel_x: 160,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "boulder_g_1_1",
            pixel_x: 176,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "boulder_d_0_0",
            pixel_x: 192,
            pixel_y: 128,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "boulder_d_0_1",
            pixel_x: 208,
            pixel_y: 128,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "boulder_d_1_0",
            pixel_x: 192,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "boulder_d_1_1",
            pixel_x: 208,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "boulder_e_0_0",
            pixel_x: 224,
            pixel_y: 128,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "boulder_e_0_1",
            pixel_x: 224,
            pixel_y: 128,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "boulder_e_1_0",
            pixel_x: 224,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "boulder_e_1_1",
            pixel_x: 240,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        // --- 2 OAK TREES ---
        // Grass Base
        TilemapSprite {
            name: "oak_g_0_0",
            pixel_x: 0,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "oak_g_0_1",
            pixel_x: 16,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "oak_g_0_2",
            pixel_x: 32,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "oak_g_0_3",
            pixel_x: 48,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "oak_g_0_4",
            pixel_x: 64,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "oak_g_1_0",
            pixel_x: 0,
            pixel_y: 160,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_1_1",
            pixel_x: 16,
            pixel_y: 160,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_1_2",
            pixel_x: 32,
            pixel_y: 160,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_1_3",
            pixel_x: 48,
            pixel_y: 160,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_1_4",
            pixel_x: 64,
            pixel_y: 160,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_2_0",
            pixel_x: 0,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_2_1",
            pixel_x: 16,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_2_2",
            pixel_x: 32,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_2_3",
            pixel_x: 48,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_2_4",
            pixel_x: 64,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_3_0",
            pixel_x: 0,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_3_1",
            pixel_x: 16,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_3_2",
            pixel_x: 32,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_3_3",
            pixel_x: 48,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_3_4",
            pixel_x: 64,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_4_0",
            pixel_x: 0,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_4_1",
            pixel_x: 16,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_4_2",
            pixel_x: 32,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_4_3",
            pixel_x: 48,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_4_4",
            pixel_x: 64,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_5_0",
            pixel_x: 0,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_5_1",
            pixel_x: 16,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_5_2",
            pixel_x: 32,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_5_3",
            pixel_x: 48,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_g_5_4",
            pixel_x: 64,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        // Dirt Base
        TilemapSprite {
            name: "oak_d_0_0",
            pixel_x: 80,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "oak_d_0_1",
            pixel_x: 96,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "oak_d_0_2",
            pixel_x: 112,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "oak_d_0_3",
            pixel_x: 128,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "oak_d_0_4",
            pixel_x: 144,
            pixel_y: 144,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "oak_d_1_0",
            pixel_x: 80,
            pixel_y: 160,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_1_1",
            pixel_x: 96,
            pixel_y: 160,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_1_2",
            pixel_x: 112,
            pixel_y: 160,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_1_3",
            pixel_x: 128,
            pixel_y: 160,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_1_4",
            pixel_x: 144,
            pixel_y: 160,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_2_0",
            pixel_x: 80,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_2_1",
            pixel_x: 96,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_2_2",
            pixel_x: 112,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_2_3",
            pixel_x: 128,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_2_4",
            pixel_x: 144,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_3_0",
            pixel_x: 80,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_3_1",
            pixel_x: 96,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_3_2",
            pixel_x: 112,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_3_3",
            pixel_x: 128,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_3_4",
            pixel_x: 144,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_4_0",
            pixel_x: 80,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_4_1",
            pixel_x: 96,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_4_2",
            pixel_x: 112,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_4_3",
            pixel_x: 128,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_4_4",
            pixel_x: 144,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_5_0",
            pixel_x: 80,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_5_1",
            pixel_x: 96,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_5_2",
            pixel_x: 112,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_5_3",
            pixel_x: 128,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "oak_d_5_4",
            pixel_x: 144,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        // --- 2 PINE TREES ---
        // Grass Base
        TilemapSprite {
            name: "pine_g_0_0",
            pixel_x: 160,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "pine_g_0_1",
            pixel_x: 176,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "pine_g_0_2",
            pixel_x: 192,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "pine_g_1_0",
            pixel_x: 160,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_1_1",
            pixel_x: 176,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_1_2",
            pixel_x: 192,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_2_0",
            pixel_x: 160,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_2_1",
            pixel_x: 176,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_2_2",
            pixel_x: 192,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_3_0",
            pixel_x: 160,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_3_1",
            pixel_x: 176,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_3_2",
            pixel_x: 192,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_4_0",
            pixel_x: 160,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_4_1",
            pixel_x: 176,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_g_4_2",
            pixel_x: 192,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        // Bare Base
        TilemapSprite {
            name: "pine_b_0_0",
            pixel_x: 208,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "pine_b_0_1",
            pixel_x: 224,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "pine_b_0_2",
            pixel_x: 240,
            pixel_y: 160,
            walkable: Walkable::NonWalkable,
        },
        TilemapSprite {
            name: "pine_b_1_0",
            pixel_x: 208,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_1_1",
            pixel_x: 224,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_1_2",
            pixel_x: 240,
            pixel_y: 176,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_2_0",
            pixel_x: 208,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_2_1",
            pixel_x: 224,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_2_2",
            pixel_x: 240,
            pixel_y: 192,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_3_0",
            pixel_x: 208,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_3_1",
            pixel_x: 224,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_3_2",
            pixel_x: 240,
            pixel_y: 208,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_4_0",
            pixel_x: 208,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_4_1",
            pixel_x: 224,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
        TilemapSprite {
            name: "pine_b_4_2",
            pixel_x: 240,
            pixel_y: 224,
            walkable: Walkable::Walkable,
        },
    ],
};
